apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
  namespace: muchtodo
type: Opaque
stringData:
  mongo-root-username: root
  mongo-root-password: example
  mongo-uri: mongodb://root:example@mongodb-service:27017/much_todo_db?authSource=admin&directConnection=true
